"""init

迁移 ID: 21f55abc2b90
父迁移: 
创建时间: 2026-09-25 15:15:23.887177

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '21f55abc2b90'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('amrita_plugin_memory',)
depends_on: str | Sequence[str] | None = '072361e8936f'


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amrita_plugin_memory_user_memo',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['amrita_user_metadata.user_id'], name=op.f('fk_amrita_plugin_memory_user_memo_user_id_amrita_user_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_amrita_plugin_memory_user_memo')),
    info={'bind_key': 'amrita_plugin_memory'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amrita_plugin_memory_user_memo')
    # ### end Alembic commands ###
